### ISSUE TITLE
sispmctl development and releases

### ISSUE THREAD

**Issue by wschlich** [xypron/sispmctl#1]
Hello Heinrich,

you seem to be the only one left who actively develops sispmctl :)
There's somebody else who wanted to port it to libusb-1.0, but he's not done more than a single commit so far: https://github.com/anlumo/sispmctl (maybe you're interested in doing that port...?).

Could you imagine turning your fork of sispmctl into "the" designated successor fork?
If yes, could you tag a new release that I could use for my Gentoo ebuild?

Cheers,
Wolfram

**Comment by xypron** [comment]
Hello Wolfram,

my commits in this fork have been imported to the master on Sourceforge (http://sourceforge.net/p/sispmctl/git/ci/master/tree/). I have been granted commit rights on SF. What would be the advantage of using libusb-1.0?

Best regards

Heinrich Schuchardt

**Comment by wschlich** [comment]
Hello Heinrich!

Ah, thank you for the headsup :)
I'll ask Pete Hildebrandt then whether he has any plans to tag a new sispmctl release anytime soon.

Regarding your question about libusb-1.0:
I only asked because I saw Andreas Monitzer started doing the port and it seemed to be a good idea to me to migrate to libusb-1.0.

I've now checked http://www.libusb.org/wiki/libusb-1.0#libusb-0.1 and found out that 1.0, compared to 0.1, provides:
- isochronous endpoint I/O
- asynchronous I/O

I have no clue whether these 2 features are of any relevance for sispmctl.
Probably they aren't? :)

So, as I can try to use the libusb-compat wrapper to run sispmctl on my libusb-1.0 system, there seems to be no actual need to port sispmctl to the libusb-1.0 API.

What do you think?

Cheers,
Wolfram

**Comment by xypron** [comment]
Hello Wolfram

libusb-1.0 is under active development. libusb-0.1 is not.
OpenWrt uses libusb-compat (see http://www.libusb.org/) to provide the libusb-0.1 API.
Debian uses llibusb-0.1.12 which dates back to 2006.

So it would make sense to migrate to libusb-1.0. I close the issue here on github.
All wishes should be posted on the SF site for sispmctl.

Best regards

Heinrich Schuchardt
