### ISSUE TITLE
Supporting Energie PMS2 USB device

### ISSUE THREAD

**Issue by Matthias84** [xypron/sispmctl#3]
Hi, I try to control a (new)  power socket device that is close to the original Gembird power socket, but a tip different. I had no luck to get it working and I'm not sure if this is only limitation of sispmctl or if I struggle with my OS (Linux Mint 19):

When I connect the plug, I see
> dmesg
> ...
> [  254.561957] usb 1-1.4: USB disconnect, device number 4
> [  256.391178] usb 1-1.4: new low-speed USB device number 5 using dwc_otg
> [  256.534487] usb 1-1.4: New USB device found, idVendor=04b4, idProduct=fd15
> [  256.534500] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
> [  256.534509] usb 1-1.4: Product: EG-PMS2
> [  256.534517] usb 1-1.4: Manufacturer: Gembird
> [  256.535530] usbhid 1-1.4:1.0: couldn't find an input interrupt endpoint
> ...

As you see, there is a new product ID 0xfd15 that is currently not within sispm_ctl.h
But also the last line seems to be a problem? I couldn't fix it as the docs at upstream suggest to load usbfs or to add an udev rule.

> lsusb
> Bus 001 Device 005: ID 04b4:fd15 Cypress Semiconductor Corp.
> ...

As you see, I can't control the unit with SiS PM Control for Linux 3.1

> sudo sispmctl -s
> No GEMBIRD SiS-PM found. Check USB connections, please!

**Comment by xypron** [comment]
@Matthias84 
Thanks for reporting the problem. I have just committed a patch that adds the new product ID. I assume that it relates this product https://energenie.com/item.aspx?id=7415

Please, confirm that your power strip has four controllable outlets.

Please, test the code with all the options mentioned in the man page including plannification.

If everything is working I will push the code upstream.

**Comment by Matthias84** [comment]
Thanks for adding this device. Please give me some time to build the update.

**Comment by xypron** [comment]
@Matthias84 
I have also added the device to https://github.com/xypron/pysispm. So you might also give this a try.

**Comment by Matthias84** [comment]
I seem to run in trouble at the build process. After `./configure && make && make install` I get:
> sispmctl 
> sispmctl: error while loading shared libraries: libsispmctl.so.0: cannot open shared object file: No such file or directory

But the library exists: /usr/local/lib/libsispmctl.so.0 and it's not getting better, if I do every step as root.
Unfortunately I don't have a lot of experience in compiling packages and it seems libtool causes this pain. Could you please help me?

**Comment by xypron** [comment]
For installation run 

```
./autogen.sh
./configure
make
sudo make install
sudo ldconfig
```

**Comment by Matthias84** [comment]
Thank you very much! I can confirm the device is working as expected :+1:
